- policyholder/schema.py
I've just fixed the issue with "parent_level" filter. I used the solution from 'Insuree' module.
> OFS-99: fixing 'location_parent_level' filter

- policyholder/schema.py
Could you merge this small change, because I made typo in location filter?
> OFS-99: fixing typo in locations filter

- policyholder/gql/gql_mutations/input_types.py
- policyholder/gql/gql_mutations/replace_mutation.py
- policyholder/gql/gql_mutations/update_mutations.py
- policyholder/schema.py
- policyholder/services.py
In that pull request I want to merge changes related with changes in 'replace' in PolicyHolder. I also allow to update some chosen fields during replacing according to mockups and docs from wiki.
Another pull requests related to this issue:
- core module: https://github.com/openimis/openimis-be-core_py/pull/29
- contribution plan module: https://github.com/openimis/openimis-be-contribution_plan_py/pull/9
> OFS-118: fixing replace mutation in PolicyHolder

- policyholder/__init__.py
- policyholder/services.py
- policyholder/tests/services/__init__.py
- policyholder/tests/services/services_ph_tests.py
In that pull request I want to merge services for PolicyHolder module. That services will be based on JSON format. I also coded decorator to check authentication etc so as to reduce lines of codes.
Moreover I made couple of tests to check whether this current solution works properly.
> OFS-98: create services for PolicyHolder module

- policyholder/gql/gql_types.py
- policyholder/models.py
In that pull request I want to merge fixing of "get_queryset" in graphQl types in PH module and moreover I've added for ROW_SECURITY=True restriction in filtering location per user.
> OFS-120: fixing get_queryset in gql_type and restrict location per user

- setup.py
In that PR I want update setup.py file. Related to test server issue
> OFS-156: adding install requires

- policyholder/schema.py
In that PR I want to fix bug with id/uuid detected by @rstencel during developing replace pOlicyHolderInsuree
> OFS-156: fixing error in bind signal with id etc

- policyholder/gql/gql_types.py
- policyholder/schema.py
In that pull request I want to fix issue with filtering in PolicyHolder module (dae_valid_from and date_valid_to).
Please not merge this until I change the status to "open". I will change the status after closing https://github.com/openimis/openimis-be-core_py/pull/34
> OFS-159: fixing date valid from/to filters in PolicyHolder module

- policyholder/tests/helpers.py
- policyholder/tests/helpers_tests.py
- policyholder/tests/services/services_ph_tests.py
In that PR I want to update tests for PolicyHolder module.
> OFS-226: fix tests

- policyholder/gql/gql_mutations/create_mutations.py
- policyholder/gql/gql_mutations/update_mutations.py
- policyholder/services.py
- policyholder/tests/helpers.py
- policyholder/tests/services/services_ph_tests.py
- policyholder/validation/__init__.py
- policyholder/validation/policyholder_validation.py
TICKET: [OFS-205](https://openimis.atlassian.net/browse/OFS-205)
> OFS-205: Validation for unique PH display name

- policyholder/schema.py
Ticket - https://openimis.atlassian.net/browse/OFS-254
1 issue from description
In that PR I want to add flag for graphQl filters "setDefaultFilter". That flag will work if neither of dates validfrom/to don't be passed into filter args.
Default value @rstencel as we determined - False
> OFS-254: fixing validity filtering in PH module

- README.md
- policyholder/schema.py
- policyholder/signals.py
- setup.py
TICKET: https://openimis.atlassian.net/browse/OFS-257
changes in payment module
- https://github.com/openimis/openimis-be-payment_py/pull/3
In that PR I want to add registering signal that will be triggered when somebody want to pass into kwargs (in graphQL) "addtionalFilter". 
example of payload in graphQL query after changes
> OFS-257: append PH into filters connected to signal

- policyholder/apps.py
- policyholder/schema.py
- policyholder/signals.py
TICKET: https://openimis.atlassian.net/browse/OFS-260
> OFS-260: Support the policyholder portal perms on Policyholder

- policyholder/gql/gql_mutations/create_mutations.py
TICKET: https://openimis.atlassian.net/browse/OFS-275
> OFS-275: Policy Holder User is not created

- policyholder/signals.py
TICKET: https://openimis.atlassian.net/browse/OFS-279
- solved point c) - user type in additional dynamic filter in "payment" query
> OFS-279: fixed bug related to user type in filter

- policyholder/signals.py
TICKET: https://openimis.atlassian.net/browse/OFS-280
> OFS-280: added condition with payments perms

- policyholder/apps.py
TICKET: https://openimis.atlassian.net/browse/OFS-281
> OFS-281: support insuree policy portal perms

- policyholder/signals.py
TICKET: https://openimis.atlassian.net/browse/OFS-284
Similar approach like did BlueSquare in filter_validity function from core module with using "now"
> OFS-284: check actual validity for PHuser

- policyholder/gql/gql_types.py
part of TICKET: https://openimis.atlassian.net/browse/OFS-291 requested by @rstencel and @delcroip 
added filter_fields for "InteractiveUser" graphQl developed by BlueSquare.
> OFS-291: adding filter_fields for InteractiveUser

- policyholder/apps.py
- policyholder/services.py
Changes:
- Added PH activity and PH legal form code systems to the module configuration
- Added services to retrieve PH activity and PH legal form code systems 
[https://openimis.atlassian.net/browse/OE0-77](https://openimis.atlassian.net/browse/OE0-77)
> OE0-77: Add OrganizationPHLegalForm and OrganizationPHActivity + update OrganizationHFLegalForm Code Systems

- policyholder/migrations/0016_policyholder_roles_for_admin.py
TICKET: https://openimis.atlassian.net/browse/OP-461
> OPL-461: added migration to add roles for admin in PolicyHolder module

- policyholder/migrations/0001_initial.py
- policyholder/models.py
> Django 3.1

- policyholder/tests/helpers.py
[https://openimis.atlassian.net/browse/OP-864](https://openimis.atlassian.net/browse/OP-864)
Changes:
- Fixed JSON fields in test data (JSONFallback field didn't check the syntax, JSONField does)
> OP-864 Fixed JSON fields in test data

- policyholder/tests/helpers.py
- policyholder/tests/helpers_tests.py
- policyholder/tests/services/services_ph_tests.py
[https://openimis.atlassian.net/browse/OP-868](https://openimis.atlassian.net/browse/OP-868)
Changes:
- Changed handling of JSON fields from JSON strings to python dictionaties (Django 3.2 update)
- Fixed TestCase handling (added all missing calls to super.setUpClass, super.setUp, removed unecessary teardowns)
- Removed some unused code/comments/imports
- Fixed code formatting
> OP-868 Fix CI issues caused by Django 3.2 update

- .github/workflows/openmis-module-test.yml
- policyholder/migrations/0001_initial.py
- policyholder/migrations/0003_auto_20201214_1239.py
- policyholder/migrations/0004_auto_20201214_1302.py
- policyholder/migrations/0011_auto_20210408_0937.py
- policyholder/migrations/0012_auto_20210408_0949.py
- policyholder/migrations/0013_auto_20210408_0951.py
- policyholder/migrations/0014_auto_20210408_1007.py
- policyholder/migrations/0016_policyholder_roles_for_admin.py
- policyholder/models.py
- policyholder/tests/helpers.py
- policyholder/tests/helpers_tests.py
- policyholder/tests/services/services_ph_tests.py
MERGING RELEASE branches
Release release/22.10
> MERGING RELEASE branches

- .github/workflows/openmis-module-test.yml
- policyholder/gql/gql_mutations/create_mutations.py
- policyholder/gql/gql_mutations/delete_mutations.py
- policyholder/gql/gql_mutations/replace_mutation.py
- policyholder/gql/gql_mutations/update_mutations.py
- policyholder/schema.py
- policyholder/validation/permission_validation.py
https://openimis.atlassian.net/browse/OTC-878
> OTC-878: add permission to gql mutations and queries

- policyholder/gql/gql_mutations/input_types.py
Ticket: https://openimis.atlassian.net/browse/OP-931
FE PR: https://github.com/openimis/openimis-fe-policyholder_js/pull/62
Changes:
- Fixed input type for replace PHI mutation.
> OP-931: Replace PHI fix.

- policyholder/gql/gql_mutations/create_mutations.py
- policyholder/schema.py
- policyholder/services.py
Ticket: https://openimis.atlassian.net/browse/OP-1373
Changes:
- Backend now blocks creating PH with the same code
- Query for FE validation added.
> OP-1373: Policy holder code validation.

- policyholder/schema.py
[https://openimis.atlassian.net/browse/CM-190](https://openimis.atlassian.net/browse/CM-190)
> CM-190 Fixed filtering for policy_holder query

- policyholder/apps.py
https://openimis.atlassian.net/browse/OP-1518
This PR changes the way how config is loaded.
> OP-1518: load config

- policyholder/management/commands/generatepolicyholders.py
https://openimis.atlassian.net/browse/PSI-10
This PR add ability to generate policyholders for performance testing.
> PCI-10: generate demo policyholders

- policyholder/models.py
- tatus
Fixed broken locationmanager query
> Fixed policyholder locationmanager query

- policyholder/tests/helpers.py
- policyholder/tests/services/services_ph_tests.py
MERGING develop into release/24.04
> MERGING develop into release/24.04

- policyholder/tests/helpers.py
MERGING release/24.04 into develop
> MERGING release/24.04 into develop
